// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/liuzhaomax/maxblog-sgw/internal/api"
	"github.com/liuzhaomax/maxblog-sgw/internal/core"
	"github.com/liuzhaomax/maxblog-sgw/internal/middleware"
	"github.com/liuzhaomax/maxblog-sgw/internal/middleware/auth"
	"github.com/liuzhaomax/maxblog-sgw/internal/middleware/reverse_proxy"
	"github.com/liuzhaomax/maxblog-sgw/internal/middleware/tracing"
	"github.com/liuzhaomax/maxblog-sgw/internal/middleware/validator"
)

// Injectors from wire.go:

func InitInjector() (*Injector, func(), error) {
	engine := core.InitGinEngine()
	logger := core.InitLogrus()
	coreLogger := &core.Logger{
		Logger: logger,
	}
	client, cleanup, err := core.InitRedis()
	if err != nil {
		return nil, nil, err
	}
	authAuth := &auth.Auth{
		Logger: coreLogger,
		Redis:  client,
	}
	validatorValidator := &validator.Validator{
		Logger: coreLogger,
		Redis:  client,
	}
	configuration := core.InitTracer()
	tracingTracing := &tracing.Tracing{
		Logger:       coreLogger,
		TracerConfig: configuration,
	}
	reverseProxy := &reverse_proxy.ReverseProxy{
		Logger:      coreLogger,
		RedisClient: client,
	}
	middlewareMiddleware := &middleware.Middleware{
		Auth:         authAuth,
		Validator:    validatorValidator,
		Tracing:      tracingTracing,
		ReverseProxy: reverseProxy,
	}
	registry := core.InitPrometheusRegistry()
	handler := &api.Handler{
		Middleware:         middlewareMiddleware,
		PrometheusRegistry: registry,
	}
	injector := &Injector{
		Engine:  engine,
		Handler: handler,
		Redis:   client,
	}
	return injector, func() {
		cleanup()
	}, nil
}
